# https://github.com/updownpress/markdown-lint/blob/master/rules/003-header-style.md
# MD003 - Header style
# Specify `setext_with_atx` that means h1 and h2 with underline and others with hashes.
header-style:
  style: setext_with_atx

# https://github.com/updownpress/markdown-lint/blob/master/rules/007-ul-indent.md
# MD007 - Unordered list indentation
# Disable because some Markdown parsers use 4 spaces for lists.
ul-indent: false

# https://github.com/updownpress/markdown-lint/blob/master/rules/009-no-trailing-spaces.md
# MD009 - Trailing spaces
# Disable because trailing whitespaces are checked by textlint.
no-trailing-spaces: false

# https://github.com/updownpress/markdown-lint/blob/master/rules/013-line-length.md
# MD013 - Line length
# Disable because I don't want to break lines after a certain number of characters.
line-length: false

# https://github.com/updownpress/markdown-lint/blob/master/rules/024-no-duplicate-header.md
# MD024 - Multiple headers with the same content
# Disable because sometimes header texts are the same.
no-duplicate-header: false

# https://github.com/updownpress/markdown-lint/blob/master/rules/026-no-trailing-punctuation.md
# MD026 - Trailing punctuation in header
# Allow exclamation marks and question marks and disallow Japanese punctuations.
no-trailing-punctuation:
  # Default: ".,;:!?"
  punctuation: ".,;:、。；："

# https://github.com/updownpress/markdown-lint/blob/master/rules/029-ol-prefix.md
# MD029 - Ordered list item prefix
# Disable because I usually want to use only `1.` but sometimes want to use other numbers.
ol-prefix: false

# https://github.com/updownpress/markdown-lint/blob/master/rules/033-no-inline-html.md
# MD033 - Inline HTML
# Disable because sometimes I want to use some HTML tags.
no-inline-html: false

# https://github.com/updownpress/markdown-lint/blob/master/rules/034-no-bare-urls.md
# MD034 - Bare URL used
# Disable because I don't want to surround a URL by angle brackets (`<` and `>`).
no-bare-urls: false

# https://github.com/updownpress/markdown-lint/blob/master/rules/040-fenced-code-language.md
# MD040 - Fenced code blocks should have a language specified
# Disable because sometimes the language is unnecessary.
fenced-code-language: false

# https://github.com/updownpress/markdown-lint/blob/master/rules/041-first-line-h1.md
# MD041 - First line in file should be a top level header
# Disable because sometimes the content starts with non-h1.
first-line-h1: false
