# see `pt --help`

# Output Options
color   = true
context = 1
group   = true

# Search Options
e                = true
smart-case       = true
skip-vcs-ignores = true
hidden           = true
follow           = true

# Ignores
ignore = [
  ".cache",
  ".DS_Store",
  ".git",
  ".hg",
  ".svn",
  ".vim-sessions",
  "log",
  "node_modules",
  "tmp",

  "*_structure.sql",
  "*.dat",
  "*.diff",
  "*.min.js",
  "tags",
]
