inherit_mode:
  merge:
    - Exclude
    - Include

require:
  - rubocop-performance

AllCops:
  EnabledByDefault: true
  Include:
    - ".*/**/pryrc"
    - "Gemfile.local.example"

Bundler/GemComment:
  Enabled: false
Bundler/GemVersion:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/SingleLineBlockChain:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Lint/ConstantResolution:
  Enabled: false
Lint/NumberConversion:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Naming/FileName:
  Exclude:
    - "Gemfile.local.example"

Performance/ChainArrayAllocation:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic
Style/ClassAndModuleChildren:
  Enabled: false
Style/CollectionMethods:
  Enabled: false
Style/ConstantVisibility:
  Enabled: false
Style/Copyright:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/ImplicitRuntimeError:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
Style/MissingElse:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/Next:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/StringHashKeys:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
