---
include:
  - "**/*.rb"
require:
  - actionmailer
  - actionpack
  - actionview
  - activemodel
  - activerecord
  - activesupport
require_paths:
  - test
  - test/lib
  - test/support
reporters:
  # Use other language server for rubocop
  # - rubocop
  - require_not_found
