---
include:
  - "**/*.rb"
exclude:
  - "vendor/**/*"
require: []
reporters:
  # Valid sources are sometimes not found by solargraph.
  # - require_not_found

  # Use an other language server for rubocop
  # - rubocop

  # https://solargraph.org/guides/type-checking
  - typecheck:typed
formatter: {}
require_paths: []
plugins: []
max_files: 10000
