cmdargs:
  verbose: false
  severity: style_problem
  error-limit: 50
  stat: true
  color: true
  json: false
  env:
    neovim: false
  stdin_display_name: stdin
policies:
  ProhibitAutocmdWithNoGroup:
    enabled: true
  ProhibitCommandRelyOnUser:
    enabled: true
  ProhibitCommandWithUnintendedSideEffect:
    enabled: true
  ProhibitEncodingOptionAfterScriptEncoding:
    enabled: true
  ProhibitEqualTildeOperator:
    enabled: true
  ProhibitImplicitScopeBuiltinVariable:
    enabled: true
  ProhibitMissingScriptEncoding:
    enabled: true
  ProhibitNoAbortFunction:
    enabled: true
  ProhibitSetNoCompatible:
    enabled: true
  ProhibitUnnecessaryDoubleQuote:
    enabled: false
  ProhibitUnusedVariable:
    enabled: true
  ProhibitUsingUndeclaredVariable:
    enabled: true
