version: 2
provide-definition: false

tools:
  actionlint: &actionlint
    prefix: actionlint
    lint-command: "$HOME/.config/efm-langserver/actionlint_wrapper.sh '${INPUT}'"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

  checkmake: &checkmake
    prefix: checkmake
    lint-command: "checkmake"
    lint-stdin: true

  cspell: &cspell
    prefix: CSpell
    lint-command: "cspell 'stdin://${INPUT}'"
    # severity: 3 = Information
    lint-severity: 3
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c - %m"

  erb: &erb
    prefix: ERB
    lint-command: "$HOME/.config/efm-langserver/erb_wrapper.sh"
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%l:%m"

  erb-lint: &erb-lint
    prefix: ERB Lint
    lint-command: "$HOME/.config/efm-langserver/erblint_wrapper.sh '${INPUT}'"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

  eslint: &eslint
    prefix: ESlint
    lint-command: "$HOME/.config/efm-langserver/eslint_wrapper.sh '${INPUT}'"
    lint-stdin: true
    lint-formats:
      - "%l:%c:%t%*[a-z]: %m"
    format-command: "$HOME/.config/efm-langserver/eslint_wrapper.sh '${INPUT}' --fix"
    format-stdin: true

  lit-analyzer: &lit-analyzer
    prefix: lit-analyzer
    lint-command: "$HOME/.config/efm-langserver/lit_analyzer_wrapper.sh '${INPUT}'"
    lint-formats:
      - "%*[ ]%l:%c%*[ ]%t%*[a-z]%*[ ]%m"

  markdownlint: &markdownlint
    prefix: markdownlint
    lint-command: "markdownlint --stdin --config $HOME/.config/markdownlint/config.yaml"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c %m"
      - "%f:%l %m"
      - "%f: %l: %m"

  markuplint: &markuplint
    prefix: Markuplint
    lint-command: "$HOME/.config/efm-langserver/markuplint_wrapper.sh '${INPUT}'"
    # Using stdin is supported according to markuplint's help, but it doesn't work
    # lint-stdin: true
    lint-formats:
      - "%l:%c %m"

  prettier: &prettier
    format-command: "$HOME/.config/efm-langserver/prettier_wrapper.sh '${INPUT}'"
    format-stdin: true

  rubocop: &rubocop
    prefix: RuboCop
    lint-command: "$HOME/.config/efm-langserver/rubocop_wrapper.sh '${INPUT}'"
    lint-category-map:
      C: W  # Convention
      E: E  # Error
      F: E  # Fatal
      R: W  # Refactor
      W: W  # Warning
    lint-stdin: true
    lint-formats:
      - "%t:%l:%c: %m"
    format-command: "$HOME/.config/efm-langserver/rubocop_wrapper.sh '${INPUT}' --fix"
    format-stdin: true

  ruby: &ruby
    prefix: Ruby
    lint-command: "$HOME/.config/efm-langserver/ruby_wrapper.sh '${INPUT}'"
    lint-formats:
      - "%l: %tarning: %m"
      - "%l: %m"

  shellcheck: &shellcheck
    prefix: ShellCheck
    lint-command: "shellcheck --shell=bash --format=gcc --external-sources --enable=all -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %t%*[a-z]: %m"

  shfmt: &shfmt
    format-command: "shfmt -i 2 -ci -sr -kp -filename '${INPUT}'"
    format-stdin: true

  slim-lint: &slim-lint
    prefix: Slim-Lint
    lint-command: "slim-lint --stdin-file-path '${INPUT}'"
    lint-stdin: true
    lint-formats:
      - "%f:%l [%t] %m"

  sql-formatter: &sql-formatter
    format-command: "$HOME/.config/efm-langserver/sql_formatter_wrapper.sh"
    format-stdin: true

  stylelint: &stylelint
    prefix: Stylelint
    lint-command: "$HOME/.config/efm-langserver/stylelint_wrapper.sh '${INPUT}'"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m [%t%*[a-z]]"

  textlint: &textlint
    prefix: textlint
    lint-command: "$HOME/.config/efm-langserver/textlint_wrapper.sh '${INPUT}'"
    lint-stdin: true
    lint-formats:
      - "%l:%c:%t%*[a-z]: %m"
    format-command: "$HOME/.config/efm-langserver/textlint_wrapper.sh '${INPUT}' --fix"
    format-stdin: true

  typos: &typos
    prefix: typos
    lint-command: "typos --format brief -"
    # severity: 3 = Information
    lint-severity: 3
    lint-stdin: true
    lint-formats:
      - "-:%l:%c: %m"

  vint: &vint
    prefix: Vint
    lint-command: "vint -"
    lint-stdin: true

  yamllint: &yamllint
    prefix: yamllint
    lint-command: "yamllint --format parsable --strict -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: [%t%*[a-z]] %m"

languages:
  =:
    - <<: *cspell
    - <<: *typos

  Gemfile:
    - <<: *rubocop
    - <<: *ruby

  css:
    - <<: *stylelint
    - <<: *prettier

  eruby:
    - <<: *erb
    - <<: *erb-lint
    - <<: *markuplint

  eruby.yaml:
    - <<: *yamllint

  gitcommit:
    - <<: *textlint

  html:
    - <<: *markuplint
    - <<: *prettier

  javascript:
    - <<: *eslint
    - <<: *lit-analyzer
    - <<: *markuplint
    - <<: *prettier

  javascriptreact:
    - <<: *eslint
    - <<: *lit-analyzer
    - <<: *markuplint
    - <<: *prettier

  json:
    - <<: *prettier

  jsonc:
    - <<: *prettier

  make:
    - <<: *checkmake

  markdown:
    - <<: *markdownlint
    - <<: *prettier
    - <<: *rubocop
    - <<: *textlint

  ruby:
    - <<: *rubocop
    - <<: *ruby

  scss:
    - <<: *stylelint
    - <<: *prettier

  sh:
    - <<: *shellcheck
    - <<: *shfmt

  slim:
    - <<: *slim-lint

  sql:
    - <<: *sql-formatter

  typescript:
    - <<: *eslint
    - <<: *lit-analyzer
    - <<: *markuplint
    - <<: *prettier

  typescriptreact:
    - <<: *eslint
    - <<: *lit-analyzer
    - <<: *markuplint
    - <<: *prettier

  vim:
    - <<: *vint

  vue:
    - <<: *markuplint
    - <<: *prettier

  yaml:
    - <<: *actionlint
    - <<: *yamllint
    - <<: *prettier

  zsh:
    - <<: *shellcheck
    # Disable because shfmt sometimes fails to parse or freezes.
    # - <<: *shfmt
