version: 2

tools:
  erb: &erb
    lint-command: "erb -x -T - | ruby -c"
    lint-stdin: true
    lint-offset: 0

  jq: &jq
    lint-command: "jq ."

  checkmake: &checkmake
    lint-command: "checkmake"
    lint-stdin: true

  markdownlint: &markdownlint
    lint-command: "markdownlint --stdin"
    lint-stdin: true
    lint-formats:
      - "%f: %l: %m"
      - "%f:%l %m"

  textlint: &textlint
    lint-command: "textlint --format unix --stdin"
    lint-formats:
      - "%f:%l:%n: %m"

  shellcheck: &shellcheck
    lint-command: "shellcheck --shell=bash --format=gcc --external-sources --enable=all -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

  vint: &vint
    lint-command: "vint -"
    lint-stdin: true

  yamllint: &yamllint
    lint-command: "yamllint --format parsable --strict -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: [%trror] %m"
      - "%f:%l:%c: [%tarning] %m"

languages:
  eruby:
    - <<: *erb

  eruby.yaml:
    - <<: *yamllint

  json:
    - <<: *jq

  make:
    - <<: *checkmake

  markdown:
    - <<: *markdownlint
    - <<: *textlint

  sh:
    - <<: *shellcheck

  vim:
    - <<: *vint

  yaml:
    - <<: *yamllint

  zsh:
    - <<: *shellcheck
