version: 2

commands:
  - title: reload config
    command: ":reload-config"

  # cf. tools.shfmt
  - title: shfmt
    command: "shfmt -i 2 -ci -sr -kp -w '${INPUT}'"

tools:
  checkmake: &checkmake
    lint-command: "checkmake"
    lint-stdin: true

  erb: &erb
    lint-command: "erb -x -T - | ruby -c"
    lint-stdin: true
    lint-offset: 0

  eslint: &eslint
    lint-command: "$HOME/.config/efm-langserver/eslint_wrapper.sh '${INPUT}'"
    lint-stdin: true
    lint-formats:
      - "%l:%n:%trror: %m"
      - "%l:%n:%tarning: %m"
    format-command: "$HOME/.config/efm-langserver/eslint_wrapper.sh '${INPUT}' --fix"
    format-stdin: true

  jq: &jq
    lint-command: "jq ."

  markdownlint: &markdownlint
    lint-command: "markdownlint --stdin"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c %m"
      - "%f:%l %m"
      - "%f: %l: %m"

  shellcheck: &shellcheck
    lint-command: "shellcheck --shell=bash --format=gcc --external-sources --enable=all -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

  # cf. commands.shfmt
  shfmt: &shfmt
    format-command: "shfmt -i 2 -ci -sr -kp -filename '${INPUT}'"
    format-stdin: true

  textlint: &textlint
    lint-command: "$HOME/.config/efm-langserver/textlint_wrapper.sh '${INPUT}'"
    lint-stdin: true
    lint-formats:
      - "%l:%n:%trror: %m"
      - "%l:%n:%tarning: %m"

  vint: &vint
    lint-command: "vint -"
    lint-stdin: true

  yamllint: &yamllint
    lint-command: "yamllint --format parsable --strict -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: [%trror] %m"
      - "%f:%l:%c: [%tarning] %m"

languages:
  eruby:
    - <<: *erb

  eruby.yaml:
    - <<: *yamllint

  javascript:
    - <<: *eslint

  json:
    - <<: *jq

  make:
    - <<: *checkmake

  markdown:
    - <<: *markdownlint
    - <<: *textlint

  sh:
    - <<: *shellcheck
    - <<: *shfmt

  typescript:
    - <<: *eslint

  # Disable because modern syntaxes are not supported
  # vim:
  #   - <<: *vint

  yaml:
    - <<: *yamllint

  zsh:
    - <<: *shellcheck
    # Disable because shfmt sometimes fails to parse or freezes. Use `shfmt` code action instead if needed.
    # - <<: *shfmt
