EnableDefaultLinters: true
linters:
  FinalNewline:
    enabled: false
  # https://github.com/Shopify/erb-lint#selfclosingtag
  # Disable because closing tag style for void elements are still common.
  SelfClosingTag:
    enabled: false
