ZSH_THEME_GIT_PROMPT_PREFIX="["
ZSH_THEME_GIT_PROMPT_SUFFIX="]"
ZSH_THEME_GIT_PROMPT_SEPARATOR="|"
ZSH_THEME_GIT_PROMPT_DETACHED="%{$fg_bold[cyan]%}:"
ZSH_THEME_GIT_PROMPT_BRANCH="%{$fg_bold[magenta]%}"
ZSH_THEME_GIT_PROMPT_BEHIND="v"
ZSH_THEME_GIT_PROMPT_AHEAD="^"
ZSH_THEME_GIT_PROMPT_UNMERGED="%{$fg[red]%}C"
ZSH_THEME_GIT_PROMPT_STAGED="%{$fg[blue]%}+"
ZSH_THEME_GIT_PROMPT_UNSTAGED="%{$fg[yellow]%}!"
ZSH_THEME_GIT_PROMPT_UNTRACKED="?"
ZSH_THEME_GIT_PROMPT_STASHED="%{$fg[cyan]%}*"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg_bold[green]%}#"
ZSH_GIT_PROMPT_SHOW_STASH=1

zplugin ice silent pick"git-prompt.zsh"; zplugin light woefe/git-prompt.zsh
