abbrevs:
  # cf. .config/zsh/aliases.zsh
  - name: "G => | rg"
    abbr: G
    snippet: "| rg"
    global: true
  - name: "V => | vim -R -"
    abbr: V
    snippet: "| vim -R -"
    global: true
  - name: "L => | less"
    abbr: L
    snippet: "| less"
    global: true
  - name: "H => | head"
    abbr: H
    snippet: "| head"
    global: true
  - name: "T => | tail"
    abbr: T
    snippet: "| tail"
    global: true
  - name: "F => | filter"
    abbr: F
    snippet: "| filter"
    global: true
  - name: "S => | sort_without_escape_sequences"
    abbr: S
    snippet: "| sort_without_escape_sequences"
    global: true

  - name: bmv => batch_move
    abbr: bmv
    snippet: batch_move

  - name: brew i => brew install
    abbr: i
    snippet: install
    global: true
    context: '^brew\s'
  - name: brew li => brew list
    abbr: li
    snippet: list
    global: true
    context: '^brew\s'
  - name: brew uni => brew uninstall
    abbr: uni
    snippet: uninstall
    global: true
    context: '^brew\s'

  - name: b => bundle
    abbr: b
    snippet: bundle
  - name: bundle e => bundle exec
    abbr: e
    snippet: exec
    global: true
    context: '^bundle\s'
  - name: bundle i => bundle install
    abbr: i
    snippet: install
    global: true
    context: '^bundle\s'
  - name: bundle pr => bundle pristine
    abbr: pr
    snippet: pristine
    global: true
    context: '^bundle\s'
  - name: bundle up => bundle update
    abbr: up
    snippet: update
    global: true
    context: '^bundle\s'

  - name: cdb => cd-bookmark
    abbr: cdb
    snippet: cd-bookmark

  - name: d => docker
    abbr: d
    snippet: docker
  - name: dc => docker-compose
    abbr: dc
    snippet: docker-compose
  - name: docker c => docker compose
    abbr: c
    snippet: compose
    global: true
    context: '^docker\s'
  - name: docker e => docker exec
    abbr: e
    snippet: exec
    global: true
    context: '^docker\s'

  - name: f => filter
    abbr: f
    snippet: filter

  - name: gem h => gem help
    abbr: h
    snippet: help
    global: true
    context: '^gem\s'
  - name: gem i => gem install
    abbr: i
    snippet: install
    global: true
    context: '^gem\s'
  - name: gem li => gem list
    abbr: li
    snippet: list
    global: true
    context: '^gem\s'
  - name: gem uni => gem uninstall
    abbr: uni
    snippet: uninstall
    global: true
    context: '^gem\s'
  - name: gem up => gem update
    abbr: up
    snippet: update
    global: true
    context: '^gem\s'

  - name: g => git
    abbr: g
    snippet: git
  - name: git bl => git blame-with-filter
    abbr: bl
    snippet: blame-with-filter
    global: true
    context: '^git\s'
  - name: git br => git branch
    abbr: br
    snippet: branch
    global: true
    context: '^git\s'
  - name: git brs => git branches
    abbr: brs
    snippet: branches
    global: true
    context: '^git\s'
  - name: git co => git checkout
    abbr: co
    snippet: checkout
    global: true
    context: '^git\s'
  - name: git cp => git cherry-pick
    abbr: cp
    snippet: cherry-pick
    global: true
    context: '^git\s'
  - name: git p => git cherry-pick
    abbr: p
    snippet: cherry-pick
    global: true
    context: '^git\s'
  - name: git pick => git cherry-pick
    abbr: pick
    snippet: cherry-pick
    global: true
    context: '^git\s'
  - name: git ci => git commit
    abbr: ci
    snippet: commit
    global: true
    context: '^git\s'
  - name: git di => git diff-without-space-changes
    abbr: di
    snippet: diff-without-space-changes
    global: true
    context: '^git\s'
  - name: git ds => git diff-without-space-changes --staged
    abbr: ds
    snippet: diff-without-space-changes --staged
    global: true
    context: '^git\s'
  - name: git dh => git diff-without-space-changes HEAD
    abbr: dh
    snippet: diff-without-space-changes HEAD
    global: true
    context: '^git\s'
  - name: git f => git fetch
    abbr: f
    snippet: fetch
    global: true
    context: '^git\s'
  - name: git l => git log-by-select
    abbr: l
    snippet: log-by-select
    global: true
    context: '^git\s'
  - name: git lg => git log-graph
    abbr: lg
    snippet: log-graph
    global: true
    context: '^git\s'
  - name: git la => git log --branches --tags --remotes
    abbr: la
    snippet: log --branches --tags --remotes
    global: true
    context: '^git\s'
  - name: git lp => git log-with-patch
    abbr: lp
    snippet: log-with-patch
    global: true
    context: '^git\s'
  - name: git st => git status-with-color
    abbr: st
    snippet: status-with-color
    global: true
    context: '^git\s'
  - name: git ss => git stash
    abbr: ss
    snippet: stash
    global: true
    context: '^git\s'
  - name: git ssa => git stash-all-with-message
    abbr: ssa
    snippet: stash-all-with-message
    global: true
    context: '^git\s'
  - name: git sss => git stash-by-select
    abbr: sss
    snippet: stash-by-select
    global: true
    context: '^git\s'
  - name: git sw => git switch
    abbr: sw
    snippet: switch
    global: true
    context: '^git\s'
  - name: git sws => git switch-by-select
    abbr: sws
    snippet: switch-by-select
    global: true
    context: '^git\s'
  - name: git up => git update
    abbr: up
    snippet: update
    global: true
    context: '^git\s'

  - name: ls => eza
    abbr: ls
    snippet: eza "${EZA_DEFAULT_OPTIONS[@]}"
  - name: ll => eza --long
    abbr: ll
    snippet: eza "${EZA_DEFAULT_OPTIONS[@]}" --long --header --git
  - name: lt => eza --long --tree
    abbr: lt
    snippet: eza "${EZA_DEFAULT_OPTIONS[@]}" --long --header --git --tree --ignore-glob "${EZA_IGNORE_GLOB:?}"

  - name: mise -g => mise --global
    abbr: -g
    snippet: --global
    global: true
    context: '^mise\s'
  - name: mise i => mise install
    abbr: i
    snippet: install
    global: true
    context: '^mise\s'
  - name: mise uni => mise uninstall
    abbr: uni
    snippet: uninstall
    global: true
    context: '^mise\s'

  - name: npm -g => npm --global
    abbr: -g
    snippet: --global
    global: true
    context: '^npm\s'
  - name: npm i => npm install
    abbr: i
    snippet: install
    global: true
    context: '^npm\s'
  - name: npm li => npm list
    abbr: li
    snippet: list
    global: true
    context: '^npm\s'
  - name: npm uni => npm uninstall
    abbr: uni
    snippet: uninstall
    global: true
    context: '^npm\s'
  - name: npm up => npm update
    abbr: up
    snippet: update
    global: true
    context: '^npm\s'

  - name: rails c => rails console
    abbr: c
    snippet: console
    global: true
    context: '\brails\s'
  - name: rails console -e => rails console --environment
    abbr: -e
    snippet: --environment
    global: true
    context: '\brails\sconsole\s'
  - name: rails console -s => rails console --sandbox
    abbr: -s
    snippet: --sandbox
    global: true
    context: '\brails\sconsole\s'
  - name: rails db => rails dbconsole
    abbr: db
    snippet: dbconsole --include-password
    global: true
    context: '\brails\s'
  - name: rails g => rails generate
    abbr: g
    snippet: generate
    global: true
    context: '\brails\s'
  - name: rails re => rails restart
    abbr: re
    snippet: restart
    global: true
    context: '\brails\s'
  - name: rails r => rails runner
    abbr: r
    snippet: runner
    global: true
    context: '\brails\s'
  - name: rails s => rails server
    abbr: s
    snippet: server
    global: true
    context: '\brails\s'
  - name: rails t => rails test
    abbr: t
    snippet: test
    global: true
    context: '\brails\s'
  # Define after `rails runner` to avoid conflicts. Otherwise `rails r` will become `rails rails`.
  - name: r => rails
    abbr: r
    snippet: rails
    global: true
    context: "^(bundle exec )?"
  - name: bin/r => bin/rails
    abbr: bin/r
    snippet: bin/rails

  - name: di => my_diff:without_spaces
    abbr: di
    snippet: my_diff:without_spaces
  - name: gr => my_grep:with_filter
    abbr: gr
    snippet: my_grep:with_filter

  - name: t => tmux:attach_or_new
    abbr: t
    snippet: tmux:attach_or_new

  - name: v => vim
    abbr: v
    snippet: vim
  - name: vi => vim
    abbr: vi
    snippet: vim

  - name: yarn a => yarn add
    abbr: a
    snippet: add
    global: true
    context: '^yarn\s'
  # Don’t use `yarn install` because I use `yarn`.
  - name: yarn i => yarn add
    abbr: i
    snippet: add
    global: true
    context: '^yarn\s'
  - name: yarn li => yarn list
    abbr: li
    snippet: list
    global: true
    context: '^yarn\s'
  - name: yarn rem => yarn remove
    abbr: rem
    snippet: remove
    global: true
    context: '^yarn\s'
  - name: yarn uni => yarn remove
    abbr: uni
    snippet: remove
    global: true
    context: '^yarn\s'
  - name: yarn up => yarn upgrade
    abbr: up
    snippet: upgrade
    global: true
    context: '^yarn\s'
  - name: yarn upi => yarn upgrade-interactive
    abbr: upi
    snippet: upgrade-interactive
    global: true
    context: '^yarn\s'
