abbrevs:
  - name: asdf install
    abbr: i
    snippet: install
    global: true
    context: '^asdf\s'
  - name: asdf list
    abbr: li
    snippet: list
    global: true
    context: '^asdf\s'

  - name: batch_move
    abbr: bmv
    snippet: batch_move

  - name: brew install
    abbr: i
    snippet: install
    global: true
    context: '^brew\s'
  - name: brew list
    abbr: li
    snippet: list
    global: true
    context: '^brew\s'
  - name: brew uninstall
    abbr: uni
    snippet: uninstall
    global: true
    context: '^brew\s'

  - name: bundle
    abbr: b
    snippet: bundle
  - name: bundle exec
    abbr: e
    snippet: exec
    global: true
    context: '^bundle\s'
  - name: bundle install
    abbr: i
    snippet: install
    global: true
    context: '^bundle\s'
  - name: bundle pristine
    abbr: pr
    snippet: pristine
    global: true
    context: '^bundle\s'
  - name: bundle update
    abbr: up
    snippet: update
    global: true
    context: '^bundle\s'

  - name: cd-bookmark
    abbr: cdb
    snippet: cd-bookmark

  - name: docker
    abbr: d
    snippet: docker
  - name: docker-compose
    abbr: dc
    snippet: docker-compose
  - name: docker compose
    abbr: c
    snippet: compose
    global: true
    context: '^docker\s'
  - name: docker exec
    abbr: e
    snippet: exec
    global: true
    context: '^docker\s'

  - name: filter
    abbr: f
    snippet: filter

  - name: gem help
    abbr: h
    snippet: help
    global: true
    context: '^gem\s'
  - name: gem install
    abbr: i
    snippet: install
    global: true
    context: '^gem\s'
  - name: gem list
    abbr: li
    snippet: list
    global: true
    context: '^gem\s'
  - name: gem uninstall
    abbr: uni
    snippet: uninstall
    global: true
    context: '^gem\s'
  - name: gem update
    abbr: up
    snippet: update
    global: true
    context: '^gem\s'

  - name: git
    abbr: g
    snippet: git
  - name: git aliases
    abbr: alias
    snippet: aliases
    global: true
    context: '^git\s'
  - name: git blame-with-filter
    abbr: bl
    snippet: blame-with-filter
    global: true
    context: '^git\s'
  - name: git branch
    abbr: br
    snippet: branch
    global: true
    context: '^git\s'
  - name: git branches
    abbr: brs
    snippet: branches
    global: true
    context: '^git\s'
  - name: git checkout
    abbr: co
    snippet: checkout
    global: true
    context: '^git\s'
  - name: git cherry-pick-cp
    abbr: cp
    snippet: cherry-pick
    global: true
    context: '^git\s'
  - name: git cherry-pick-pick
    abbr: pick
    snippet: cherry-pick
    global: true
    context: '^git\s'
  - name: git cherry-pick-p
    abbr: p
    snippet: cherry-pick
    global: true
    context: '^git\s'
  - name: git commit
    abbr: ci
    snippet: commit
    global: true
    context: '^git\s'
  - name: git diff-without-space-changes
    abbr: di
    snippet: diff-without-space-changes
    global: true
    context: '^git\s'
  - name: git diff-without-space-changes --cached
    abbr: sc
    snippet: diff-without-space-changes --cached
    global: true
    context: '^git\s'
  - name: git diff-without-space-changes --staged
    abbr: ds
    snippet: diff-without-space-changes --staged
    global: true
    context: '^git\s'
  - name: git diff-without-space-changes --color-words
    abbr: dw
    snippet: diff-without-space-changes --color-words
    global: true
    context: '^git\s'
  - name: git diff-without-space-changes HEAD
    abbr: dh
    snippet: diff-without-space-changes HEAD
    global: true
    context: '^git\s'
  - name: git fetch
    abbr: f
    snippet: fetch
    global: true
    context: '^git\s'
  - name: git log-graph
    abbr: lg
    snippet: log-graph
    global: true
    context: '^git\s'
  - name: git log --branches --tags --remotes
    abbr: la
    snippet: log --branches --tags --remotes
    global: true
    context: '^git\s'
  - name: git log-by-select
    abbr: l
    snippet: log-by-select
    global: true
    context: '^git\s'
  - name: git log-with-patch
    abbr: lp
    snippet: log-with-patch
    global: true
    context: '^git\s'
  - name: git rebase
    abbr: r
    snippet: rebase
    global: true
    context: '^git\s'
  - name: git status-by-select
    abbr: sts
    snippet: status-by-select
    global: true
    context: '^git\s'
  - name: git status-with-color
    abbr: st
    snippet: status-with-color
    global: true
    context: '^git\s'
  - name: git stash
    abbr: ss
    snippet: stash
    global: true
    context: '^git\s'
  - name: git stash-all-with-message
    abbr: ssa
    snippet: stash-all-with-message
    global: true
    context: '^git\s'
  - name: git stash-by-select
    abbr: sss
    snippet: stash-by-select
    global: true
    context: '^git\s'
  - name: git switch
    abbr: sw
    snippet: switch
    global: true
    context: '^git\s'
  - name: git switch-by-select
    abbr: sws
    snippet: switch-by-select
    global: true
    context: '^git\s'
  - name: git update
    abbr: up
    snippet: update
    global: true
    context: '^git\s'

  - name: ls to eza
    abbr: ls
    snippet: eza "${EZA_DEFAULT_OPTIONS[@]}"
  - name: ll to eza --long
    abbr: ll
    snippet: eza "${EZA_DEFAULT_OPTIONS[@]}" --long --header --git
  - name: lt to eza --long --tree
    abbr: lt
    snippet: eza "${EZA_DEFAULT_OPTIONS[@]}" --long --header --git --tree --ignore-glob "${EZA_IGNORE_GLOB:?}"

  - name: npm install
    abbr: i
    snippet: install
    global: true
    context: '^npm\s'
  - name: npm list
    abbr: li
    snippet: list
    global: true
    context: '^npm\s'
  - name: npm uninstall
    abbr: uni
    snippet: uninstall
    global: true
    context: '^npm\s'
  - name: npm update
    abbr: up
    snippet: update
    global: true
    context: '^npm\s'

  - name: rails console
    abbr: c
    snippet: console
    global: true
    context: '\brails\s'
  - name: rails console --environment
    abbr: -e
    snippet: --environment
    global: true
    context: '\brails\sconsole\s'
  - name: rails console --sandbox
    abbr: -s
    snippet: --sandbox
    global: true
    context: '\brails\sconsole\s'
  - name: rails dbconsole
    abbr: db
    snippet: dbconsole --include-password
    global: true
    context: '\brails\s'
  - name: rails generate
    abbr: g
    snippet: generate
    global: true
    context: '\brails\s'
  - name: rails restart
    abbr: re
    snippet: restart
    global: true
    context: '\brails\s'
  - name: rails runner
    abbr: r
    snippet: runner
    global: true
    context: '\brails\s'
  - name: rails server
    abbr: s
    snippet: server
    global: true
    context: '\brails\s'
  - name: rails test
    abbr: t
    snippet: test
    global: true
    context: '\brails\s'
  # Define after `rails runner` to avoid conflicts. Otherwise `rails r` will become `rails rails`.
  - name: rails
    abbr: r
    snippet: rails
    global: true
    context: "^(bundle exec )?"
  - name: bin/rails
    abbr: bin/r
    snippet: bin/rails

  - name: my_diff:without_spaces
    abbr: di
    snippet: my_diff:without_spaces
  - name: my_grep:with_filter
    abbr: gr
    snippet: my_grep:with_filter

  - name: tmux:attach_or_new
    abbr: t
    snippet: tmux:attach_or_new

  - name: v to vim
    abbr: v
    snippet: vim
  - name: vi to vim
    abbr: vi
    snippet: vim

  - name: yarn add
    abbr: a
    snippet: add
    global: true
    context: '^yarn\s'
  # Don’t use `yarn install` because I use `yarn`.
  - name: yarn add for mistaking `yarn i`
    abbr: i
    snippet: add
    global: true
    context: '^yarn\s'
  - name: yarn list
    abbr: li
    snippet: list
    global: true
    context: '^yarn\s'
  - name: yarn remove
    abbr: rem
    snippet: remove
    global: true
    context: '^yarn\s'
  - name: yarn remove2
    abbr: uni
    snippet: remove
    global: true
    context: '^yarn\s'
  - name: yarn upgrade
    abbr: up
    snippet: upgrade
    global: true
    context: '^yarn\s'
  - name: yarn upgrade-interactive
    abbr: upi
    snippet: upgrade-interactive
    global: true
    context: '^yarn\s'
