#!/usr/bin/env bash
prev_diff="$(git log --max-count=1 --patch --format= | grep -E '^\+')"
risky_pattern='(^|(?<=\s)|(?<=;))(ap|binding\.\w+|byebug|console(?=\.)|debugger|logger(?=\.)|p?ld|pp?|puts|save_and_open_(page|screenshot)|t?ld)\b|(?<=\.)inspect\b'

if echo "${prev_diff}" | rg "${risky_pattern}" -q; then
  mark="❗"
  message="The previous diff contains risky words. Check and fix them if needed."

  printf "\n%s \e[1;31m%s\e[0;37m %s\n\n" "${mark}" "${message}" "${mark}"

  echo "${prev_diff}" | rg "${risky_pattern}"
fi

if [ -f "Gemfile.lock" ]; then
  prev_changed_files="$(git log --max-count=1 --name-only --format=)"

  # If a Rails engine's version is bumped but the `Gemfile.lock` isn't updated.
  if echo "${prev_changed_files}" | grep -E '^lib/[^/]+/version\.rb$' -q; then
    if ! echo "${prev_changed_files}" | grep -E '^Gemfile\.lock$' -q; then
      mark="❗"
      message="Gem's version has been updated but Gemfile.lock hasn't. Check if there is missing update."

      printf "\n%s \e[1;31m%s\e[0;37m %s\n\n" "${mark}" "${message}" "${mark}"
    fi
  fi
fi

if [ -f .git_templates/hooks/post-commit ]; then
  if [ "${USE_GIT_LOCAL_TEMPLATE_HOOKS:-}" = "1" ]; then
    source .git_templates/hooks/post-commit
  else
    printf "\e[1;38;5;3m%s\e[0;0m\n" "WARN -- \`.git_templates/hooks/post-commit\` exists but not allowed." >&2
  fi
else
  exit 0
fi
