#!/usr/bin/env sh
# http://klabgames.tech.blog.jp.klab.com/archives/1033121546.html

PREVIOUS_HEAD=$1
NEW_HEAD=$2
BRANCH_SWITCH=$3
Z40="0000000000000000000000000000000000000000"

# Continue only when "git clone" has been executed.
if [ "$PREVIOUS_HEAD" != "$Z40" -o "$BRANCH_SWITCH" != "1" ]; then
  exit
fi

source ~/.config/git/bin/set_user_info_depending_on_repository_url
