#!/usr/bin/env bash
# https://git-scm.com/docs/githooks#_post_checkout
previous_head="$1"
# new_head="$2"
is_branch_checkout="$3"

# https://stackoverflow.com/questions/73000182/githooks5-what-is-the-git-null-ref/73000183#73000183
NULL_REF="0000000000000000000000000000000000000000"
is_post_clone="$([ "${previous_head}" = "${NULL_REF}" ] && [ "${is_branch_checkout}" = "1" ] && echo "1" || echo "0")"

# Set user info depending the repository URL only when "git clone" has been executed.
# https://www.klab.com/jp/blog/tech/2015/1033121546.html
if [ "${is_post_clone}" = "1" ]; then
  source ~/.config/git/bin/set_user_info_depending_on_repository_url || exit 1
fi

if [ -f .git_templates/hooks/post-checkout ]; then
  if [ "${USE_GIT_LOCAL_TEMPLATE_HOOKS:-}" = "1" ]; then
    source .git_templates/hooks/post-checkout
  else
    printf "\e[1;38;5;3m%s\e[0;0m\n" "WARN -- \`.git_templates/hooks/post-checkout\` exists but not allowed." >&2
  fi
else
  exit 0
fi
