#!/usr/bin/env bash
PREVIOUS_HEAD=$1
# NEW_HEAD=$2
BRANCH_SWITCH=$3
Z40="0000000000000000000000000000000000000000"

# Continue only when "git clone" has been executed.
if [ "${PREVIOUS_HEAD}" != "${Z40}" ] || [ "${BRANCH_SWITCH}" != "1" ]; then
  exit 0
fi

source ~/.config/git/bin/set_user_info_depending_on_repository_url || exit 1

if [ -f .git_templates/hooks/post-checkout ]; then
  if [ "${USE_GIT_LOCAL_TEMPLATE_HOOKS:-}" = "1" ]; then
    source .git_templates/hooks/post-checkout
  else
    printf "\e[1;38;5;3m%s\e[0;0m\n" "WARN -- \`.git_templates/hooks/post-checkout\` exists but not allowed." >&2
  fi
else
  exit 0
fi
