#!/usr/bin/env bash
if git log --format='%s' --right-only origin/HEAD... | grep -E '^fixup\b' -q; then
  printf "\e[1;38;5;1m%s\e[0;0m\n" "ERROR -- Non-pushed fixup commits exist." >&2
  exit 1
fi

if [ -f .git_templates/hooks/pre-push ]; then
  source .git_templates/hooks/pre-push
else
  exit 0
fi
