#!/usr/bin/env bash
if [ -f .git_templates/hooks/pre-commit ]; then
  if [ "${USE_GIT_LOCAL_TEMPLATE_HOOKS:-}" = "1" ]; then
    source .git_templates/hooks/pre-commit
  else
    printf "\e[1;38;5;3m%s\e[0;0m\n" "WARN -- \`.git_templates/hooks/pre-commit\` exists but not allowed." >&2
  fi
else
  exit 0
fi
