#!/usr/bin/env bash
current_branch="$(git branch --show-current)"

if git log --format='%s' --right-only "origin/${current_branch}"... | grep -E '^fixup\b' -q; then
  printf "\e[1;38;5;1m%s\e[0;0m\n" "ERROR -- Non-pushed fixup commits exist." >&2
  exit 1
fi

if [ "${GIT_LOCAL_TEMPLATE_HOOKS_AVAILABLE:-}" = "1" ] && [ -f .git_templates/hooks/pre-push ]; then
  source .git_templates/hooks/pre-push
else
  exit 0
fi
