tap argon/mas
brew mas

tap homebrew/core
brew ack
brew autoconf
brew automake
brew colordiff
brew coreutils
brew git
brew gnu-sed
brew gnutls
brew go
brew hadoop
brew hive
brew mercurial
brew ngrep
brew nkf
brew openssl
brew peco
brew python3
brew rbenv
brew readline
brew ruby-build
brew sqlite
brew xz
brew zsh

tap peco/peco

tap rcmdnk/file
brew brew-file

# Characters which have ambiguous width are broken
# on Vim in original tmux window
tap waltarix/customs
brew waltarix/customs/tmux

appstore 430173763 Degrees
appstore 467939042 Growl
appstore 540348655 Monosnap
appstore 414445104 WindowFlow
