tap argon/mas
brew mas

tap heroku/brew
brew heroku
brew heroku-node

tap homebrew/core
brew ack
brew ansible
brew autoconf
brew automake
brew colordiff
brew coreutils
brew ctags
brew curl
brew direnv
brew git
brew gnu-sed
brew gnutls
brew go
brew hadoop
brew hive
brew jq
brew lua
brew mercurial
brew ngrep
brew nkf
brew node
brew openssl
brew peco
brew python
brew python@2
brew rbenv
brew rbenv-gemset
brew readline
brew ruby-build
brew sqlite
brew tig
brew tldr
brew xz
brew yarn
brew zsh

tap rcmdnk/file
brew brew-file

# Characters which have ambiguous width are broken
# on Vim in original tmux window
tap waltarix/customs
brew waltarix/customs/tmux

appstore 937984704 Amphetamine (3.0.2)
appstore 467939042 Growl (2.1.3)
appstore 414445104 WindowFlow (1.3.0)
