# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request
name: Dependabot Auto-merge

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Generate token
        id: generate_token
        uses: getsentry/action-github-app-token@v3
        with:
          app_id: "${{ secrets.KG8M_BOT_APP_ID }}"
          private_key: "${{ secrets.KG8M_BOT_PRIVATE_KEY }}"
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: "${{ github.event.pull_request.html_url }}"

          # Use my GitHub app’s temporary token because the default `GITHUB_TOKEN` prevents other workflows from being
          # triggered on a pull request creation.
          # cf. https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
          GH_TOKEN: "${{ steps.generate_token.outputs.token }}"
    timeout-minutes: 5
