[settings]
# Prevent the warning “authentication required but no callback set; class=Ssh (23); code=Auth (-16)”
# cf. https://github.com/jdx/mise/issues/3099
libgit2 = false

[tools]
deno = "latest"
go = "latest"
node = "latest"
postgres = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
terraform = "latest"
usage = "latest"
